all: chapter1.pdf chapter2.pdf chapter3.pdf chapter5.pdf chapter6.pdf chapter7.pdf chapter8.pdf chapter9.pdf chapter10.pdf chapter11.pdf chapter12.pdf chapter13.pdf chapter14.pdf

clean:
	rm chapter*.pdf


chapter1.pdf: ctlc.pdf
	pdftk ctlc.pdf cat 8-21 output chapter1.pdf
chapter2.pdf: ctlc.pdf
	pdftk ctlc.pdf cat 22-30 output chapter2.pdf
chapter3.pdf: ctlc.pdf
	pdftk ctlc.pdf cat 31-38 output chapter3.pdf

chapter5.pdf: ctlc.pdf
	pdftk ctlc.pdf cat 42-51 output chapter5.pdf
chapter6.pdf: ctlc.pdf
	pdftk ctlc.pdf cat 52-55 output chapter6.pdf
chapter7.pdf: ctlc.pdf
	pdftk ctlc.pdf cat 56-64 output chapter7.pdf
chapter8.pdf: ctlc.pdf
	pdftk ctlc.pdf cat 65-66 output chapter8.pdf
chapter9.pdf: ctlc.pdf
	pdftk ctlc.pdf cat 67-75 output chapter9.pdf
chapter10.pdf: ctlc.pdf
	pdftk ctlc.pdf cat 76-80 output chapter10.pdf
chapter11.pdf: ctlc.pdf
	pdftk ctlc.pdf cat 82-88 output chapter11.pdf
chapter12.pdf: ctlc.pdf
	pdftk ctlc.pdf cat 89-93 output chapter12.pdf
chapter13.pdf: ctlc.pdf
	pdftk ctlc.pdf cat 94-100 output chapter13.pdf
chapter14.pdf: ctlc.pdf
	pdftk ctlc.pdf cat 101-110 output chapter14.pdf
chapter15-draft.pdf: ctlc.pdf
	pdftk ctlc.pdf cat 111-119 output chapter15-draft.pdf
chapter16-draft.pdf: ctlc.pdf
	pdftk ctlc.pdf cat 116-124 output chapter16-draft.pdf
chapter22-draft.pdf: ctlc.pdf
	pdftk ctlc.pdf cat 142-152 output chapter22-draft.pdf
chapter23-draft.pdf: ctlc.pdf
	pdftk ctlc.pdf cat 153-158 output chapter23-draft.pdf
