all: chapter1.pdf chapter2.pdf chapter3.pdf

chapter1.pdf: ctlc.pdf
	pdftk ctlc.pdf cat 8-21 output chapter1.pdf

chapter2.pdf: ctlc.pdf
	pdftk ctlc.pdf cat 22-30 output chapter2.pdf

chapter3.pdf: ctlc.pdf
	pdftk ctlc.pdf cat 31-38 output chapter3.pdf
